CREATE TABLE users (
id INT AUTO_INCREMENT,
name VARCHAR NOT NULL,
email VARCHAR NOT NULL,
password VARCHAR NOT NULL,
dateCreated DATETIME NOT NULL,
signature VARCHAR NOT NULL,
PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE admins (
id INT AUTO_INCREMENT,
email VARCHAR NOT NULL,
password VARCHAR NOT NULL,
dateCreated DATETIME NOT NULL,
PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE awards (
id INT AUTO_INCREMENT,
userId INT NOT NULL,
type TINYINT NOT NULL,
awardee VARCHAR NOT NULL,
email VARCHAR NOT NULL,
dateAwarded DATETIME NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (userId) REFERENCES users(id)
) ENGINE = InnoDB;